### ISSUE TITLE
Automatic or easier way of sending crash logs

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#10]
App is a little crash happy. Is there an easy way to send crash logs to aid in faster bug fixing?

**Comment by bogdans-telenav** [comment]
@teemsaj 
We are using Crashlytics for automatic crash reporting. This framework should report crashes as long as you enable internet access to your device and start the app. We are receiving a lot of crashes lately on device like: iPhone 4S, iPhone 5,  iPhone 5S, iPhone 5C and we will try to fix as many as possible for the next release. 
I've seen that you have a iPhone 5C (from your other posts) so most probably you also reported some crashes.
I will close this since we already do this.

**Comment by teemsaj** [comment]
My crashes have occurred from an iPhone 6 today. I hope you have those crash logs.
