### ISSUE TITLE
App exits when pressing the camera button

### ISSUE THREAD

**Issue by andreimagic** [openstreetcam/ios#11]
iOS 9.3.5 - iPhone5C
App exits when pressing the camera button to start recording no matter if 5 or 8Mega pixels.

App not swithing to landscape mode in Map view.

**Comment by bogdans-telenav** [comment]
@andreimagic Please try again now. The release that fixed this problem was sent to iTunes on 26.08.2016 but not approved until 30.0.8.2016.
**Note:** Because of a bug #15  For the first time, before you try to record your tracks, please go to Settings -> Resolution and select the only option there 2MP.  Now the app should no longer crash when you record.
