### ISSUE TITLE
iPhone 5C, only 2mp capture?

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#15]
Potential bug to report as well;

Used to be an option to shoot either 5 or 8mp photos. Now only 2mp?

The bug: OSV was not recording new images when first started, Pulled over vehicle, went into settings, and had to reselect for 2mp. Shouldn't the app just switch over if that's the only opetion, or maybe at least prompt user?

**Comment by bogdans-telenav** [comment]
@teemsaj Because we actually encode each photo in a video, we ware constraint to drop the resolution to 2mp  on iPhone lower then iPhone 6, so the potential bug is the expected behaviour.

The reported bug is **a issue on update** from any previous version to 1.4.1.
**Reason for the bug**: Did not override previous resolution settings upon update to version 1.4.1. 
Great idea on how to make it work! I will fix it for the next release (the build will be sent to iTunes on 09.09.2016) but I will close the bug as soon as i commit the code for fixing it. Thanks for reporting this !
