### ISSUE TITLE
Upload crash and wonky behavior

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#19]
I'm attaching a crash log (I grabbed it from iOS Console)

[osvcrash.txt](https://github.com/openstreetview/ios/files/459481/osvcrash.txt)

Wonky behavior: Upon relaunching OSV, it asked if I wanted to resume uploading. I said Yes, but nothing happened. What is supposed to happen here?

**Comment by bogdans-telenav** [comment]
Basic explanation: This log is written when the app recovers from a inconsistency in file management.
Technical explanation: The log file that you provided has a line that is logged only when, after a upload, the objects saved in the database are not all deleted but all the files saved on disk are, or vice versa. 
Since you reported i worked on this so i will consider this fixed.
About the "wonky behaviour": currently the app will start uploading the files without displaying the progress if you just tap "Upload" in the menu you will get the progress screen. I will suggest a improvement here to display the actual progress screen. 
Thanks for your input, i will now close this ticket.
