### ISSUE TITLE
Stop recording button is not clear

### ISSUE THREAD

**Issue by hoylen** [openstreetcam/ios#20]
After starting a recording, the "red circle" button becomes a "red rounded-rectangle" button, and the difference is difficult to tell with a quick glance while driving. Some other color and shape would be better.

Also, it is not obvious what the functional difference between the red button and "Done" is. I suspect the red button should really be a (yellow?) pause button (two vertical rectangles)?

**Comment by teemsaj** [comment]
I think the pause icon would be a better idea. That symbol is pretty universal. Done can be replaced with a "check mark" just like Mapillary.

**Comment by bogdans-telenav** [comment]
@hoylen Personally i don't really like the "Done" button but this is what the designer provided, I opposed several times but this is it. I don't have a better option for the "dismiss this screen, I am done recording" action.
@teemsaj About the pause idea it would be as bad as the current button (witch is very much like the one in the native camera app) because you don't actually make a pause in a recording you are stoping one and you now have the option to start another one. I personally hate the check mark in the Mapillary app same considerations as for the "Done" button.
