### ISSUE TITLE
Oddball question

### ISSUE THREAD

**Issue by teemsaj** [openstreetcam/ios#21]
If this isn't the right avenue for this, please point me in the right direction to ask this question.

Been trying Mapillary for a few days now, and on top of being stable, feature wise it's pretty complete. 

So my question is, since Mapillary is also submitting images to OpenStreetMaps, why is this app being developed? 

This isn't so much a "why are you wasting your time question", rather its a "what's the thought process behind having your own version of this app?" I'm also curious why this ap exists, but there isn't a dedicated iOS app for OpenStreetMaps. 

Thanks.

**Comment by bogdans-telenav** [comment]
There is plenty of room to improve each system but if you don't have any competitor you will not strive to improve as fast as you could. 
In other words making several small changes to something is what companies always do. That's why we have google search today and we almost never hear about yahoo (and the list could go on).
I hoped i wouldn't have to answer your question but no one did so hopefully you have a answer. 
About the second part a OSM iOS dedicated app. I think that there are several companies using OSM maps in there iOS native app, and the edit mode of OSM would be a complete waist of time and resources since there are better ways to edit OSM than on mobile (desktop - JOSM). On mobile it would be very easy to make unwanted edits. Basically your can not tap using your finger tips exactly ware you would like. You could make a scroll to position feature but it is just far to painful for a user to use. 
I am not saying these are the actual reasons but this is what I personally believe.
I will close this now sorry for the late answer.

Thanks.
